//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.07 at 04:56:57 PM CEST 
//


package dk.kombit.bf.anvendersystem.operationer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import dk.kombit.bf.beskedkuvert.HaendelsesbeskedType;


/**
 * <p>Java class for ModtagBeskedInputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModtagBeskedInputType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oio:besked:kuvert:1.0}Haendelsesbesked"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModtagBeskedInputType", propOrder = {
    "haendelsesbesked"
})
public class ModtagBeskedInputType {

    @XmlElement(name = "Haendelsesbesked", namespace = "urn:oio:besked:kuvert:1.0", required = true)
    protected HaendelsesbeskedType haendelsesbesked;

    /**
     * Gets the value of the haendelsesbesked property.
     * 
     * @return
     *     possible object is
     *     {@link HaendelsesbeskedType }
     *     
     */
    public HaendelsesbeskedType getHaendelsesbesked() {
        return haendelsesbesked;
    }

    /**
     * Sets the value of the haendelsesbesked property.
     * 
     * @param value
     *     allowed object is
     *     {@link HaendelsesbeskedType }
     *     
     */
    public void setHaendelsesbesked(HaendelsesbeskedType value) {
        this.haendelsesbesked = value;
    }

}
