//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.07 at 04:56:57 PM CEST 
//


package dk.kombit.bf.anvendersystem.operationer;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the oio.sts._1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ModtagBeskedOutput_QNAME = new QName("urn:oio:sts:1.0.0", "ModtagBeskedOutput");
    private final static QName _ModtagBeskedInput_QNAME = new QName("urn:oio:sts:1.0.0", "ModtagBeskedInput");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: oio.sts._1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ModtagBeskedInputType }
     * 
     */
    public ModtagBeskedInputType createModtagBeskedInputType() {
        return new ModtagBeskedInputType();
    }

    /**
     * Create an instance of {@link ModtagBeskedOutputType }
     * 
     */
    public ModtagBeskedOutputType createModtagBeskedOutputType() {
        return new ModtagBeskedOutputType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModtagBeskedOutputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sts:1.0.0", name = "ModtagBeskedOutput")
    public JAXBElement<ModtagBeskedOutputType> createModtagBeskedOutput(ModtagBeskedOutputType value) {
        return new JAXBElement<ModtagBeskedOutputType>(_ModtagBeskedOutput_QNAME, ModtagBeskedOutputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModtagBeskedInputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sts:1.0.0", name = "ModtagBeskedInput")
    public JAXBElement<ModtagBeskedInputType> createModtagBeskedInput(ModtagBeskedInputType value) {
        return new JAXBElement<ModtagBeskedInputType>(_ModtagBeskedInput_QNAME, ModtagBeskedInputType.class, null, value);
    }

}
